
package com.kieranskvortsov.gui;

import com.formdev.flatlaf.FlatDarkLaf;
import com.kieranskvortsov.lib.ItemCustomTableModel;
import com.kieranskvortsov.lib.Item;
import com.kieranskvortsov.lib.PlanogramCustomTabelModel;
import com.kieranskvortsov.lib.Processor;
import java.awt.Color;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author      Kieran Skvortsov
 * @employee#   72141
 * 
 * @version     1.0
 * @date        08.29.2022
 */
public class GUI extends javax.swing.JFrame {
    
    private static Processor processor = new Processor();
    private static ItemCustomTableModel itemCTM = new ItemCustomTableModel();
    private static PlanogramCustomTabelModel planogramCTM = new PlanogramCustomTabelModel();
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
        processor.attachLog(textAreaOutput);

        tableItems.setModel(itemCTM);
        tableItems.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        tableItems.getColumnModel().getColumn(0).setPreferredWidth(60);
        tableItems.getColumnModel().getColumn(1).setPreferredWidth(80);
        tableItems.getColumnModel().getColumn(2).setPreferredWidth(110);
        tableItems.getColumnModel().getColumn(3).setPreferredWidth(320);
        tableItems.getColumnModel().getColumn(5).setPreferredWidth(153);
        
        for(int i = 0; i < tableItems.getColumnCount(); ++i)
            tableItems.getColumnModel().getColumn(i).setResizable(false);
        
        
        tablePlanograms.setModel(planogramCTM);
        tablePlanograms.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        tablePlanograms.getColumnModel().getColumn(0).setPreferredWidth(60);
        tablePlanograms.getColumnModel().getColumn(1).setPreferredWidth(390);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        scrollPaneOutput = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        panelGroupBottom = new javax.swing.JPanel();
        buttonSearch = new javax.swing.JButton();
        comboBoxSearchType = new javax.swing.JComboBox<>();
        textfieldInput = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        scrollPaneItemTable = new javax.swing.JScrollPane();
        tableItems = new javax.swing.JTable();
        buttonOpen = new javax.swing.JButton();
        buttonPrint = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePlanograms = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PlanogramFinder");
        setName("frameMain"); // NOI18N
        setResizable(false);

        textAreaOutput.setEditable(false);
        textAreaOutput.setBackground(new java.awt.Color(51, 51, 51));
        textAreaOutput.setColumns(20);
        textAreaOutput.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        textAreaOutput.setRows(5);
        scrollPaneOutput.setViewportView(textAreaOutput);

        panelGroupBottom.setBackground(new java.awt.Color(51, 51, 51));
        panelGroupBottom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        buttonSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSearch.setText("SEARCH");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        comboBoxSearchType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SKU", "UPC", "WORD" }));
        comboBoxSearchType.setMinimumSize(new java.awt.Dimension(72, 34));

        textfieldInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textfieldInput.setMargin(new java.awt.Insets(3, 3, 3, 3));
        textfieldInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldInputActionPerformed(evt);
            }
        });

        buttonClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonClear.setText("CLEAR");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGroupBottomLayout = new javax.swing.GroupLayout(panelGroupBottom);
        panelGroupBottom.setLayout(panelGroupBottomLayout);
        panelGroupBottomLayout.setHorizontalGroup(
            panelGroupBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroupBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGroupBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGroupBottomLayout.createSequentialGroup()
                        .addComponent(textfieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGroupBottomLayout.setVerticalGroup(
            panelGroupBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGroupBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGroupBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSearchType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableItems.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        tableItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Print", "UPC", "SKU", "Description", "Fixture", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableItems.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableItems.setGridColor(new java.awt.Color(51, 51, 51));
        tableItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableItems.setShowGrid(true);
        tableItems.setShowVerticalLines(false);
        scrollPaneItemTable.setViewportView(tableItems);

        buttonOpen.setBackground(new java.awt.Color(153, 153, 153));
        buttonOpen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonOpen.setForeground(new java.awt.Color(51, 51, 51));
        buttonOpen.setText("UPLOAD");
        buttonOpen.setMaximumSize(new java.awt.Dimension(26, 26));
        buttonOpen.setMinimumSize(new java.awt.Dimension(26, 26));
        buttonOpen.setPreferredSize(new java.awt.Dimension(26, 26));
        buttonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpenActionPerformed(evt);
            }
        });

        buttonPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonPrint.setText("PRINT");
        buttonPrint.setMaximumSize(new java.awt.Dimension(26, 26));
        buttonPrint.setMinimumSize(new java.awt.Dimension(26, 26));
        buttonPrint.setPreferredSize(new java.awt.Dimension(26, 26));
        buttonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPrintActionPerformed(evt);
            }
        });

        tablePlanograms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Include", "Planogram"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePlanograms);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(panelGroupBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scrollPaneItemTable, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPaneOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneItemTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(buttonOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelGroupBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpenActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "PDF Files", "pdf");
        fileChooser.setFileFilter(filter);
        int returnVal = fileChooser.showOpenDialog(null);

        File f = null;
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            f = fileChooser.getSelectedFile();

            try {
                processor.parse(f);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, ex);
                return;
            }
        }
        
        if(f == null) return;
        
        planogramCTM.addPlanogram(f);
        
        textfieldInput.selectAll();
        textfieldInput.requestFocus();
    }//GEN-LAST:event_buttonOpenActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        int selectionIndex = comboBoxSearchType.getSelectedIndex();
        String selection = comboBoxSearchType.getItemAt(selectionIndex);

        Processor.SearchType type = null;

        if(selection.equals("UPC"))         type = Processor.SearchType.UPC;
        else if (selection.equals("SKU"))   type = Processor.SearchType.SKU;
        else if (selection.equals("WORD"))  type = Processor.SearchType.WORD;

        String digits = textfieldInput.getText();
        Item[] itemsFound = processor.search(digits, type);

        itemCTM.clearTable();
        
        for(Item i : itemsFound)
            itemCTM.addItem(i);
        
        itemCTM.updateTable();
        
        textfieldInput.selectAll();
        textfieldInput.requestFocus();
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void textfieldInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldInputActionPerformed
        buttonSearchActionPerformed(evt);
        textfieldInput.selectAll();
    }//GEN-LAST:event_textfieldInputActionPerformed

    private void buttonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPrintActionPerformed
        itemCTM.clearTable();
        
        if(itemCTM.getItemsKept().isEmpty()) {
            textAreaOutput.append("Nothing selected to print\n");
            return;
        }
        
        JTextPane printPane = new JTextPane();
        printPane.setFont(new Font(Font.MONOSPACED, Font.BOLD, 10));
        printPane.setForeground(Color.black);
        printPane.setBackground(Color.white);
        
        printPane.setText(processor.getPrintableSheet(itemCTM.getItemsKept()));
        
        try {
            printPane.print();
            textAreaOutput.append("File printed successfully\n");
        } catch (PrinterException ex) {
            textAreaOutput.append(ex.getMessage());
        }
    }//GEN-LAST:event_buttonPrintActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        itemCTM.clearTable();
    }//GEN-LAST:event_buttonClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonOpen;
    private javax.swing.JButton buttonPrint;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JComboBox<String> comboBoxSearchType;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelGroupBottom;
    private javax.swing.JScrollPane scrollPaneItemTable;
    private javax.swing.JScrollPane scrollPaneOutput;
    private javax.swing.JTable tableItems;
    private javax.swing.JTable tablePlanograms;
    private javax.swing.JTextArea textAreaOutput;
    private javax.swing.JTextField textfieldInput;
    // End of variables declaration//GEN-END:variables
}
